"""Add payment tracking to expenses

Revision ID: 38443b58e7a1
Revises: 3f948342eb7f
Create Date: 2025-06-26 15:31:34.380120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38443b58e7a1'
down_revision = '3f948342eb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=32), nullable=False, server_default='Efectivo'))
        batch_op.create_foreign_key('fk_expense_paid_by_user', 'user', ['paid_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expense_paid_by_user', type_='foreignkey')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('paid_by_user_id')

    # ### end Alembic commands ###
