"""Make phone number required and unique for clients

Revision ID: 3be9ef770053
Revises: b7d2226a90db
Create Date: 2025-06-26 15:09:17.439357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be9ef770053'
down_revision = 'b7d2226a90db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)
        batch_op.drop_index(batch_op.f('ix_client_phone_number'))
        batch_op.create_index(batch_op.f('ix_client_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_phone_number'))
        batch_op.create_index(batch_op.f('ix_client_phone_number'), ['phone_number'], unique=False)
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=1)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###
