"""Add cash closure and employee delivery models

Revision ID: 3f948342eb7f
Revises: 3be9ef770053
Create Date: 2025-06-26 15:13:42.532975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f948342eb7f'
down_revision = '3be9ef770053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_closure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('closure_date', sa.DateTime(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=False),
    sa.Column('total_expenses', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=True),
    sa.Column('delivered_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('received_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivered_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_closure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_closure_closure_date'), ['closure_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_closure_delivered_date'), ['delivered_date'], unique=False)

    op.create_table('employee_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_closure_id', sa.Integer(), nullable=False),
    sa.Column('delivered_amount', sa.Float(), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('difference', sa.Float(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('delivered_by_user_id', sa.Integer(), nullable=False),
    sa.Column('received_by_user_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cash_closure_id'], ['cash_closure.id'], ),
    sa.ForeignKeyConstraint(['delivered_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_delivery')
    with op.batch_alter_table('cash_closure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_closure_delivered_date'))
        batch_op.drop_index(batch_op.f('ix_cash_closure_closure_date'))

    op.drop_table('cash_closure')
    # ### end Alembic commands ###
