"""add tier to room model

Revision ID: 3fdf13e5cc27
Revises: 38443b58e7a1
Create Date: 2025-06-27 02:46:05.759097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdf13e5cc27'
down_revision = '38443b58e7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=True)

    # Add tier column with default value for SQLite compatibility
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=50), nullable=False, server_default='Estándar'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('tier')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)

    # ### end Alembic commands ###
