"""add inventory lifecycle models

Revision ID: b5b05831531c
Revises: 3fdf13e5cc27
Create Date: 2025-06-27 16:20:04.222165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b05831531c'
down_revision = '3fdf13e5cc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_supply_defaults',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supply.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'supply_id')
    )
    op.create_table('supply_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=True),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.Column('usage_type', sa.String(length=50), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stay_id'], ['stay.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supply.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='Activa'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('supply_usage')
    op.drop_table('room_supply_defaults')
    # ### end Alembic commands ###
