"""Add Supply model for inventory management

Revision ID: b7d2226a90db
Revises: 2fdd5b3488b2
Create Date: 2025-06-26 14:32:51.646358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d2226a90db'
down_revision = '2fdd5b3488b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('supplier', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_name'))
        batch_op.drop_index(batch_op.f('ix_supply_last_updated'))
        batch_op.drop_index(batch_op.f('ix_supply_category'))

    op.drop_table('supply')
    # ### end Alembic commands ###
